# Generated by Django 5.0.4 on 2024-04-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_carinventory_alter_car_model_year_alter_car_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
