# Generated by Django 5.0.4 on 2024-04-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='plate',
        ),
        migrations.AddField(
            model_name='car',
            name='km',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
