# Generated by Django 5.0.4 on 2024-04-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_car_plate_car_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='factory_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
