# Generated by Django 5.0.4 on 2024-04-23 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_alter_carwish_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarWish',
        ),
    ]
